routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
	
// use controller
// Route::get('/nyobak', 'JaranController@index');

// //use controller
// //memunculkan function "home"
// Route::get('/nyobak2', 'JaranController@home');

// // Customer
// Route::get('/Customer', 'CustomerController@index');
// Route::get('/Customer/create', 'CustomerController@create');
// Route::get('/Customer/store', 'CustomerController@store');
Route::resource('Customer', 'CustomerController');

Route::resource('Supplier', 'SupplierController');

Route::resource('Karyawan', 'KaryawanController');

Route::resource('Employee', 'EmployeeController');

Route::get('/Home', 'HomeController@index');

// //Supplier
// Route::get('/Supplier', 'SupplierController@index');

// // //Karyawan
// Route::get('/Karyawan', 'KaryawanController@index');

// //Products
// Route::get('/Products', 'ProductsController@index');
 
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'EmployeeController@index');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
	//
    protected $table = 'customer';

    //default id
    protected $primaryKey = 'customer_id';

    public $timestamps = false;
    //attribute
    protected $fillable = [
    	'customer_id', 
    	'name', 
    	'addres'
    ];

}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Customer;

class CustomerController extends Controller
{
    function index(){
    	//echo 'hello world, u can access controller ~';

    	$customer = Customer::get(['customer_id', 
    		'name', 
    		'addres']);

    	//var_dump($customer);
    	// return view('customer.index', compact('customer'));
        return response()->json($customer);
    }



    function create(){
    	return view('customer.create');
    }


    function store(Request $request){
        $validator = Validator::make($request->all(), [
            'customer_id' => 'required|string|max:12',
            'name' => 'required|string|max:100',
            'addres' => 'required|string|max:225',
            
        ])->validate();

    	// echo 'cobak';
    	$txtId = $request->input('txt_id');
    	$txtName = $request->input('txt_name');
    	$txtAddress = $request->input('txt_address');

    	// echo $txtId."<br>".$txtName."<br>".$txtAddress;

    	Customer::create([
    		'customer_id' => $txtId, 
    		'name' => $txtName, 
    		'addres' => $txtAddress
    	]);

    	return redirect('/Customer');
    }

    public function show($id) {
        // //ibarat (select * from Customer where customer_id = $id)
        // return view('customer.show', ['customer' => Customer::where('customer_id', $id)]);

        $customer = Customer::where('customer_id', $id)->get();
        return view('customer.show', compact('customer'));
    }

    public function edit($id) {
        // return view('customer/edit', ['customer' => Customer::where('customer_id', $id)]);

        $customer = Customer::where('customer_id', $id)->get();
        return view('customer.edit', compact('customer'));
    }

    public function update(Request $request, $id) {
        
        $txtId = $request->input('txt_id');
        $txtName = $request->input('txt_name');
        $txtAddress = $request->input('txt_address');

        Customer::where('customer_id', $id)->update([
            'name' => $txtName,
            'addres' => $txtAddress
        ]);

        return redirect('/Customer');
    }

    public function destroy($id){
        $customer = Customer::where('customer_id', $id)->first();
        $customer->delete();
        return redirect('/Customer');
    }
}

resources/views/Customer/create.blade.php
<form action="/Customer" method="post">
	{{ csrf_field() }}
	
	<label for="txt_id">Id</label>
	<input type="text" name="txt_id" id="txt_id"> <br>
	<label for="txt_name">Nama</label>
	<input type="text" name="txt_name"> <br>
	<label for="txt_address">Alamat</label>
	<input type="text" name="txt_address"> <br>
	
	<input type="submit" name="sbm_save" id="sbm_save" value="Simpan">
</form>

resources/views/Customer/edit.blade.php
@foreach ($customer as $customer_list)
			
	<form action="{{ route('Customer.update', $customer_list->customer_id) }}" method="post">
				
		{{ csrf_field() }} {{ method_field('PUT') }}


		<input type="text" name="txt_name" value="{{ $customer_list->name }}"> <br>
		<input type="text" name="txt_address" value="{{ $customer_list->addres }}"> <br>

		<button type="submit">Submit</button> <br>

	</form>

	<a href="{{ url('Customer') }}">Index</a>

@endforeach

resources/views/Customer/index.blade.php
@extends('layouts.sb-admin')

@section('home')
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Customer</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        
                    <div class="panel panel-default">
                        <div class="panel-heading">
                         Tabel Customer
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table">
                                	
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Alamat</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	@foreach ($customer as $customer_list)
                                        <tr>
                                            <td>{{$customer_list->customer_id}}</td>
                                            <td>{{$customer_list->name}}</td>
                                            <td>{{$customer_list->addres}}</td>
                                            <td><a href="/Customer/{{$customer_list->customer_id}}">Show</a></td>
                                            <td><a href="/Customer/{{$customer_list->customer_id}}/edit">Edit</a></td>
                                            <td><form action="/Customer/{{$customer_list->customer_id}}" method="post">{{ csrf_field() }} {{ method_field('DELETE') }}<button>X</button></form></td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                    
                                </table>
                                <h3><a href="/Customer/create">Create Data</a></h3>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->

    </div>
@endsection

resources/views/Customer/show.blade.php
@foreach ($customer as $customer_list)

	{{$customer_list->customer_id}}</p>
	{{$customer_list->name}} <br>
	{{$customer_list->addres}} <br>

@endforeach

<br><a href="/Customer/create">Create Data</a>